Finalized instructions for new functions exercise.
NSS-Software-Engineering/jumpstart-cohort-2 pull request #8
Opened 2022-03-21 02:53 UTC by mKroogz

Please look over these changes and the instructions for the new exercise to see if you find them acceptable. :)

2022-03-21 13:26 UTC, askingalot requested changes

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +# Exercise - Rolling Dice
Copy / Paste error?

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +    #print Hello, World!
I would just put the real code here

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +        #print Hello, World!
Again, just put the code here

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +Do you see the difference between the print and the return?  The print happens in the function while we're still waking up, but the return is for after the function is finished.....so we've already w
This is good.

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +    def get_up():
maybe `get_out_of_bed()` to better distinguish it from `wake_up()`?

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +        # print that we're waking up
It's good not to have the real code here, but I think we need a `<details>` section to reveal the code in case a student is still confused.

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +1. Okay.  So now that we've made these functions, lets call them in our `main()` function.  Remember that when we return anything from a function we need to store that return in a variable to be able
Again I think we need a `<details>` section here to demonstrate how to assign a variable to the return value of a function.

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +Once you've made the changes, run the program a few times to make sure it's working.
I don't think they need to run it "a few times" since it will always do exactly the same thing. Saying this might setup an expectation that it will do something different each time.

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +        # print that we're brushing our teeth with "toothpaste"
putting `"toothpaste"` in quotes makes it seem like a string instead of a variable.
Maybe we need an example of what the printout might look like with a few different types of toothpaste?

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +Write some code **INSIDE** a get_dressed function that prompts the user for what clothes they want to wear, and then prompts them for what shoes they will wear as well.
Again, this feels like a place for a `<details>` section.

2022-03-21 13:26 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +## Phase Seven
Things get **significantly** more complex at this point, and, honestly, I'm not sure I understand what you're going for. I think these last three phases could use further explanation, an animated gif and shoudl probably be marked as a "challenge".

2022-03-21 13:49 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +# Exercise - Rolling Dice
WHOOPS

2022-03-21 13:54 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +Do you see the difference between the print and the return?  The print happens in the function while we're still waking up, but the return is for after the function is finished.....so we've already w
:)

2022-03-21 13:55 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +    def get_up():
I agree!  I was being lazy with typing all that out haha.

2022-03-21 15:18 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +Once you've made the changes, run the program a few times to make sure it's working.
Good catch :D

2022-03-21 15:32 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +1. Okay.  So now that we've made these functions, lets call them in our `main()` function.  Remember that when we return anything from a function we need to store that return in a variable to be able
Added a nice section on that.

2022-03-21 15:34 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +        # print that we're brushing our teeth with "toothpaste"
added :)

2022-03-21 17:12 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +> **NOTE:** It may seem unnecessary to do this, but it's good practice to use functions to organize your code.
It might be worth referencing the lightning exercise here since this idea has been introduced there.  Something like "This is another example of some patterns we saw in the [lightning exercise](lightning_exercises.md#some-takeaways) about keeping our code organized."

2022-03-21 17:14 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +1. Add a new function called wake_up. It should take no parameters yet, but don't worry we'll get there. The function should, like our hello world function, print `I'm waking up!`  Next, we want to r
`wake_up` ? (monospace)

2022-03-21 17:16 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +Do you see the difference between the print and the return?  The print happens in the function while we're still waking up, but the return is for after the function is finished.....so we've already w
I would stick with 3 periods whenever you use this - e.g. (`it is finished ... so we've`)

2022-03-21 17:24 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +1. Add a new function called wake_up. It should take no parameters yet, but don't worry we'll get there. The function should, like our hello world function, print `I'm waking up!`  Next, we want to r
This reads to me like we're going to come back and make this function take parameters. Maybe something like "It should take no parameters, we're starting with a simple function and will incorporate parameters in the next step.".  Or you could also just leave it at "It should take no parameters".

2022-03-21 17:25 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +    ```python
Or maybe it needs to be indented once more?  I'm not sure :-)  I just noticed the list #'s are all 1 too so somehow markdown isn't seeing the right things (lists and blocks are tricky to get working all correctly together).

2022-03-21 17:41 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +Do we see whats happening there?  Look really closely!  When we call `hello` our function prints `'Hello, World!'`, but it **returns** a string saying its our turn.  With that return we can store or
s/unseful/useful/

2022-03-21 17:42 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +1. Let's go through that process one more time with getting out of bed!
I would maybe add a little extra description here. It wasn't immediately clear to me what the task was for this step.

2022-03-21 17:43 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +Now that we're out of bed, It's time to brush our teeth and eat some breakfast! Write some code in our main function prompting the user for what toothpaste they'll use and what breakfast they'll eat.
Maybe make this a bulleted item for consistency with other phases?

2022-03-21 17:45 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +Write some code **INSIDE** a get_dressed function that prompts the user for what clothes they want to wear, and then prompts them for what shoes they will wear as well.
`get_dressed`? (monospace)

2022-03-21 17:47 UTC, cpenner461 commented on sessions/session5/classroom/morning_routine.md
> +Write some code **INSIDE** a get_dressed function that prompts the user for what clothes they want to wear, and then prompts them for what shoes they will wear as well.
I wonder if this would be a little more clear as "Write a function called `get_dressed` that contains code that prompts..." ?

2022-03-21 18:01 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +> **NOTE:** It may seem unnecessary to do this, but it's good practice to use functions to organize your code.
Fixed :D

2022-03-21 18:01 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +1. Add a new function called wake_up. It should take no parameters yet, but don't worry we'll get there. The function should, like our hello world function, print `I'm waking up!`  Next, we want to r
good catch fixed that

2022-03-21 18:03 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +Do we see whats happening there?  Look really closely!  When we call `hello` our function prints `'Hello, World!'`, but it **returns** a string saying its our turn.  With that return we can store or
good catch fixed that :)

2022-03-21 18:08 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +1. Let's go through that process one more time with getting out of bed!
Added more instructions!

2022-03-21 19:59 UTC, askingalot requested changes

2022-03-21 19:59 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +def hello():
Do you mean this to be a `hello()` function? 

If so, I think this is confusing:
> Hint: I've written code below to demonstrate what that looks like :)

2022-03-21 19:59 UTC, askingalot commented on sessions/session5/classroom/morning_routine.md
> +1. Now that we're out of bed, It's time to brush our teeth and eat some breakfast! Write some code in our main function prompting the user for what toothpaste they'll use and what breakfast they'll e
Be more specific about the names of the variables and that they should use the `input()` function.

2022-03-21 21:32 UTC, mKroogz commented on sessions/session5/classroom/morning_routine.md
> +def hello():
fixed the phrasing around this

2022-03-22 12:51 UTC, askingalot approved these changes

2022-03-22 15:31 UTC, merged